### ISSUE TITLE
deploy each itest in its own model

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#108]
I think deploying all itests in the same model is not a justification but rather something to avoid.
The introduction of `deploy_traefik_if_not_deployed` and `deploy_charm_if_not_deployed` seems to me like an antipattern that should be avoided.

In the past we were trying out [`reset`](https://pythonlibjuju.readthedocs.io/en/latest/api/juju.model.html?highlight=reset#juju.model.Model.reset) but it wasn't very stable. If we add a `preserve` keyword to `reset` perhaps we could try again.

_Originally posted by @sed-i in https://github.com/canonical/traefik-k8s-operator/pull/103#discussion_r1034949188_

**Comment by sed-i** [comment]
Related: https://github.com/juju/python-libjuju/issues/776

**Comment by dstathis** [comment]
This is old and we are making plans for this sort of thing across all charms.
