### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#125]
### Bug Description

Occasionally an itest fails on gh (but not locally)

- Deploying tcp-tester hangs on GH, failing CI: https://github.com/canonical/traefik-k8s-operator/actions/runs/3930911566/jobs/6721504709
- test_charm_ipa.py::test_deployment OSError9: https://github.com/canonical/traefik-k8s-operator/actions/runs/3936201040/jobs/6732544673

### To Reproduce

Run CI on gh

### Environment

CI

### Relevant log output

```shell
INFO     juju.model:model.py:2715 Waiting for model:
  tcp-tester/0 [allocating] waiting: installing agent
=========================== short test summary info ============================
ERROR tests/integration/test_tcp_ipu_compatibility.py::test_tcp_ipu_compatibility - asyncio.exceptions.TimeoutError: Timed out waiting for model:
```

**Comment by lucabello** [comment]
We think this is fixed, let's reopen it if not!
