### ISSUE TITLE
Ingress-per-app is in reality ingress-by-leader

### ISSUE THREAD

**Issue by simskij** [canonical/traefik-k8s-operator#159]
### Bug Description

Currently, ingress-per-app does not really do ingressing per application using the service loadbalancer. Rather, it always routes to the leader. See https://github.com/canonical/traefik-k8s-operator/blob/34a0aa5ca57bf2d2200a37d3f884b8a13b0d4920/lib/charms/traefik_k8s/v1/ingress.py#L509-L510

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

### Additional context

See https://github.com/jnsgruk/hello-kubecon/pull/16 for example.

**Comment by PietroPasotti** [comment]
I will pick this item up next week.

**Comment by PietroPasotti** [comment]
Fixed in #200 : ingress v2 is now 'true' ingress-per-app.
TODO: add ingress-per-leader proper, instead of forcing charms who want ingress-per-leader to use ingress v1
