### ISSUE TITLE
HTTPS endpoint in databag

### ISSUE THREAD

**Issue by nsklikas** [canonical/traefik-k8s-operator#176]
### Bug Description

Even after tls is enabled the http endpoint is provided in the databag. This is not the behavior I would expect.

Applications related to traefik need to be aware of when HTTPS is enabled so that they can advertise that endpoint.

I would be happy to open a PR with a fix for this, if we reach an agreement on the behavior of the charm.

### To Reproduce

I did the following steps to deploy my charms, but simpler deployments can probably be found:
```
juju deploy traefik-k8s traefik-public 
juju deploy kratos --channel edge --trust
juju deploy tls-certificates-operator
juju deploy postgresql-k8s --channel edge --trust

juju config tls-certificates-operator ca-common-name=demo.ca.local generate-self-signed-certificates=true

juju integrate kratos postgresql-k8s
juju integrate kratos:public-ingress traefik-public
juju integrate traefik-public tls-certificates-operator
```

The contents of the databag can be seens by running:
```
juju show-unit kratos/0
```

### Environment

This was tested using juju=3.1.2 and microk8s=v1.27.1 with the metallb plugin to provide an ip address to traefik.

### Relevant log output

```shell
- relation-id: 8
    endpoint: admin-ingress
    related-endpoint: ingress
    application-data:
      ingress: |
        url: http://10.64.140.43:80/test-kratos
    related-units:
      traefik-admin/0:
        in-scope: true
        data:
          egress-subnets: 10.64.140.43/32
          ingress-address: 10.64.140.43
          private-address: 10.64.140.43
```

**Comment by rbarry82** [comment]
Closed in favor of #177
