### ISSUE TITLE
After reboot - traefik takes 10 min to get gateway address back leaving ops in agony

### ISSUE THREAD

**Issue by erik78se** [canonical/traefik-k8s-operator#181]
### Enhancement Proposal

Oh, an observation is that after a reboot - it takes almost 10 minutes until traefik gets its gateway address back (at least in juju status, See image). An operator (such as me) will think that the installation is broken and starts to worry... That is until it automagically resolves itself.... @0x12b @ppasotti 

Here is a link to a discussion about this on Juju mattermost: https://chat.charmhub.io/charmhub/pl/m1qfum9onbb1ud3fxa78capi1e

Here is a screenshot on how the situation looks like for about 10 minutes after me rebooting my computer.

![image](https://github.com/canonical/traefik-k8s-operator/assets/850603/3d291aa4-6bb2-40d6-939d-5f31fcbf28cf)

Not sure if this is a bug, but it was sure to the degree I thought it was broken until it pops back online after 10 minutes (of agony).

**Comment by simskij** [comment]
I suspect this issue is out of our control, meaning that it is dictated by metallb. However, we'll confirm and get back to you. 👍🏼

**Comment by erik78se** [comment]
I suspect that you are right. But perhaps it could be detected and put out
as a message to the ops.

It would reduce the agony for us.

/Erik

Den ons 31 maj 2023 16:09Simon Aronsson ***@***.***> skrev:

**Comment by simskij** [comment]
This is indeed out of control and is dependent on k8s (or in this case metallb) actually assigning an external ip to the loadbalancer service.
