### ISSUE TITLE
scenario tests will use pytest

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#185]
> scenario exposes a pytest plugin, and I've not yet seen unittest + scenario in action, so yeah, still TBD but if it were up to me you know what I'd pick :)

_Originally posted by @PietroPasotti in https://github.com/canonical/traefik-k8s-operator/pull/172#discussion_r1219666545_

**Comment by simskij** [comment]
Closing this one as they serve somewhat different purposes. We already have decided on using `scenario` where applicable.
