### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/traefik-k8s-operator#19]
In the `ingress_per_unit` [docstring](https://github.com/canonical/traefik-k8s-operator/blob/main/lib/charms/traefik_k8s/v0/ingress_per_unit.py#L19) we say:

> ## Getting Started
> To get started using the library, you just need to fetch the library using `charmcraft`. **Note
> that you also need to add the `serialized_data_interface` dependency to your charm's
> `requirements.txt`.**
> ```shell
> cd some-charm
> charmcraft fetch-lib charms.traefik-k8s.v0.ingress_per_unit
> echo "serialized_data_interface" >> requirements.txt
> ```

If requirements.txt has no newline at end of file this leads to an error in the file, for instance:

```
ops
kubernetes
requests
lightkube
lightkube-models
aiohttpserialized_data_interface
```

**Comment by mmanciop** [comment]
The SDI requirement will be removed when solving #28, so we can park this issue until then.
