### ISSUE TITLE
`scheme` callable is horrible UX

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#205]
### Enhancement Proposal

right now, in ingress v2, we need to pass `scheme` in as a callable to avoid timing bugs, as our charms decide what scheme to use based on the presence/config of other relations.

**Comment by Abuelodelanada** [comment]
It's partially implemented in #232 
https://github.com/canonical/traefik-k8s-operator/pull/232/files#diff-739e50d32a5a65d89cde876926a12946a218106c7b90a8800e9eeeb3d45d15a7R677

**Comment by PietroPasotti** [comment]
dropping as obsolete and an alternative is already implemented
