### ISSUE TITLE
Sometimes two `yaml` config files are present for the same app

### ISSUE THREAD

**Issue by sed-i** [canonical/traefik-k8s-operator#225]
### Bug Description

Occasionally, when removing a relation and then re-relating, the old config yaml remains on disk, such that after re-relate we have two yaml files, potentially different, causing "Internal error" etc.

### To Reproduce

On the `ingress` relation, remove relation and re-relate multiple times until it happens

### Environment

Juju 3.2, latest charms.

### Relevant log output

```shell
Don't have at hand.
```

**Comment by PietroPasotti** [comment]
can repro with a simple scenario, working on a fix

**Comment by PietroPasotti** [comment]
going at it for a half hour manually and I don't seem able to reproduce consistently

**Comment by lucabello** [comment]
Closing because we can't reproduce this.
