### ISSUE TITLE
Remove the `serialized_data_interface` dependency

### ISSUE THREAD

**Issue by jnsgruk** [canonical/traefik-k8s-operator#24]
At present, this charm depends on the [`serialized-data-interface`](https://github.com/canonical/serialized-data-interface) (SDI) library to perform version negotiation and schema validation on relation data.

While this has some attractive properties, the implementation is such that it obscures the way that relations are actually formed, and how charms really communicate through the use of 'relation data bags'. Concepts such as `requests` and `responses` do not really exist in the context of relations, and including such language will be confusing to the ecosystem.

Juju will soon include the native ability to perform some of the function that SDI aims to provide, and this charm is likely to proliferate beyond just internal Canonical products, and as such we should aim to implement what we need using constructs natively available in `ops`.

My suggestion is that we fix `ingress-per-unit` first, and then `ingress` - in line with the Observability team's current priorities.

**Comment by jnsgruk** [comment]
Key points for discussion:

- Version checking or not? We can still validate relation data bag contents and surface reasonable errors without
  - If possible, I'd like to move away from explicit versioning. It is not in the Juju core, and it is likely to cause us issues later
- Validation of relation *role* and relation *limits*
- Validation of schema for relation data bag contents

**Comment by mmanciop** [comment]
There is also the relation `meta` validation: relation interface, relation role and relation limit. See https://github.com/canonical/prometheus-k8s-operator/blob/98ec8278fda13bf23091ffab18d00b23ebceeada/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L372 and related code for an example of we perform this validation in other charm libs.

**Comment by mmanciop** [comment]
About "Version checking or not" oh yes! Each of these issues, on their own, effectively warrant a new version to work properly:

* #6
* #7
* #18
