### ISSUE TITLE
Scheme is missing from static_configs

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#273]
Scheme is missing.
But we need to think about the topology we target here:
- for in cluster scrape (by the same prom that is proxied by trfk?), we would need to use `insecureSkipVerify`, as the cert that would be served is for the external hostname.
- for out-of-cluster scrape, we would need to give the external hostname and need prom/gagent to have a `receive-ca-cert` relation (relate to the external ca)

_Originally posted by @sed-i in https://github.com/canonical/traefik-k8s-operator/pull/269#discussion_r1352548090_

**Comment by lucabello** [comment]
@PietroPasotti is this still relevant?
