### ISSUE TITLE
bump to traefik 3

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#291]
### Enhancement Proposal

[traefik 3 has been released](https://doc.traefik.io/traefik/master/migration/v2-to-v3/). 
The charm should probably deploy v3.

**Comment by lucabello** [comment]
We should start trying out the release candidate they have for v3 and try to adapt the charm to it.

**Comment by mmkay** [comment]
Note: remember about canonical/traefik-rock#28 when upgrading.
