### ISSUE TITLE
Make ingress-per-app compatible with ops 2.10.0

### ISSUE THREAD

**Issue by natalian98** [canonical/traefik-k8s-operator#293]
### Enhancement Proposal

Ingress-per-unit relies on `ops 2.10` behaviour that breaking relations don't show up in `model.relations`.
A similar fix is needed for ingress-per-app, see [this](https://matrix.to/#/!nHXpRkcSNJHlHdUGbQ:ubuntu.com/$ErTS5kMpHIVyvW8yG0qVOlYCJQNz5r3PtJZup6nDDUs?via=ubuntu.com&via=matrix.org) conversation for reference.

**Comment by PietroPasotti** [comment]
By looking at the traceback, I don't see how ingress-per-app is related.
I think the issue you're having is that adding a relation to the harness doesn't automatically add a network for it, which the library (rightfully) expects. 
Are you saying this changed with some recent release of ingress, or of ops?

Maybe it's behaviour that has changed in ops 2.10 with respect to 2.9, but I don't recall seeing anything about this.

**Comment by PietroPasotti** [comment]
Fixed by: https://github.com/canonical/operator/pull/1138
