### ISSUE TITLE
Disable checkNewVersion

### ISSUE THREAD

**Issue by nsklikas** [canonical/traefik-k8s-operator#314]
### Bug Description

The treafik flag `global.checknewversion` defaults to true. The charm does not set this flag. This means that periodically traefik tries to check if there is a new version but it fails due to a missing ca cert. 

I believe that this is unintentional and the `checkNewVersion` should be always set to false. Feel free to close this issue if that's not the case.

### To Reproduce

Deploy traefik

### Environment

juju

### Relevant log output

```shell
level=warning msg="Error checking new version: Get \"https://update.traefik.io/repos/traefik/traefik/releases\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

**Comment by lucabello** [comment]
This should indeed be set to false.
