### ISSUE TITLE
Create new LoadBalancer svc instead of modifying the Juju ClusterIP svc

### ISSUE THREAD

**Issue by kian99** [canonical/traefik-k8s-operator#319]
### Bug Description

~~This bug report doesn't necessarily need a fix in Traefik but there is some behaviour which could be changed to improve an underlying Juju bug.~~

Currently (seen in Juju 3.1.6) when a Traefik unit is unable to connect to a Juju controller the `LoadBalancer` svc that Traefik created reverts to a `ClusterIP` as mentioned in [this PR](https://github.com/canonical/observability-libs/pull/46). In one observed cloud (Openstack/PS6) this triggers the existing load balancer on the cloud to be deleted and when the service is patched, returning the svc type from `ClusterIP` to `LoadBalancer`, the LB in the cloud no longer exists.

The current fix for this in the above scenario is to manually run `kubectl patch svc cos-ingress -p '{"metadata":{"annotations":{"loadbalancer.openstack.org/load-balancer-id":null}}}'` and have Traefik request a new LB.

Some relevant information on why this happens is available in [this discussion](https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$no68NcU0maYUsnz7zBZ_89Xdo81xzRLvGDttptmOANw?via=ubuntu.com&via=matrix.org&via=mx.aouss.it) but quoting the relevant bits
> A controller restart will cause juju to rewrite/patch the resources it thinks it owns. Anything which updates those juju manahed resources from behind juju's back will cause trouble.

It seems in light of the above that the Traefik operator shouldn't be modifying the existing `ClusterIP` service that Juju creates but rather create a separate `LoadBalancer` resource with the same selector as the one currently used. This would prevent the svc from being updated when Juju "resets" things.

~~To avoid the above manual operation the operator could detect when the cloud is returning a 404 for the requested LB and clear the `load-balancer-id` annotation so that a new load balancer is automatically requested. Alternatively the existing behaviour may be desirable as it makes it easier to debug these issues on the cloud which are out of the operator's control.~~

### To Reproduce

WIP

### Environment

Juju: v3.1.6
traefik-k8s: latest/stable  166

### Relevant log output

```shell
-
```

### Additional context

Relevant Juju bug https://bugs.launchpad.net/juju/+bug/2059411

**Comment by kian99** [comment]
Renaming/rewording this bug with new information.

**Comment by gregory-schiano** [comment]
FYI we're affected by this issue on our COS deployment, currently more or less every week we loose our Octavia LB and have to manually patch the service (remove the lb ID annotation) and make a DNS PR to change the IP and sometimes do a FW PR

**Comment by sed-i** [comment]
Waiting for followup from juju team. @wallyworld
