### ISSUE TITLE
Allow traefik to use ACME http challenge for letsencrypt certificates

### ISSUE THREAD

**Issue by dparv** [canonical/traefik-k8s-operator#376]
### Enhancement Proposal

Traefik does support this option https://doc.traefik.io/traefik/https/acme/ so it ideally the charm should implement this so that traefik can request a tls certificate configured in a FQDN config option, serve the tokens under `.well-known/acme-challenge/<TOKEN>` and acquire the certificate and assign to the service while enabling TLS.

**Comment by dstathis** [comment]
There are tls_certificate providers that implement this. That is what should be used for letsencrypt. https://charmhub.io/?q=acme
