### ISSUE TITLE
`traefik_route_k8s` lib should be owned by traefik-k8s-operator

### ISSUE THREAD

**Issue by mmkay** [canonical/traefik-k8s-operator#379]
### Enhancement Proposal

Most of the issues we're getting for `traefik_route_k8s` library are reported in this repository, although officially it's [traefik-route-k8s-operator](https://github.com/canonical/traefik-route-k8s-operator)  that owns this charm library.

There was a fix we did in `traefik_route_k8s` by accident on this repository (see #325) and it wasn't noticed so this fix also was never released. 

It looks like owning `traefik_route_k8s` by this charm might be closer to the real use and reduce confusion.

**Comment by dstathis** [comment]
This is done.
