### ISSUE TITLE
Consider abstracting schema validation logic from `ingress_per_unit`

### ISSUE THREAD

**Issue by jnsgruk** [canonical/traefik-k8s-operator#38]
Right now the schema validation logic all lives inside the `ingress-per-unit` lib. As we move toward solving #37, we will likely need to solve very similar (if not the same) problems. As much of that serialisation/validation logic should be taken out into a lib of its own, and tested separately such that it can be reused here, and elsewhere.

(It may not end up living in this charm by default...)

**Comment by dstathis** [comment]
The relation interface is not, as far as I am aware, used anywhere else. So I am not sure of the value of removing the data model from the lib. Do you still think this is needed?

**Comment by jnsgruk** [comment]
I think this was a hangover from when traefik was using the SDI jank. I think this can be closed :)
