### ISSUE TITLE
cert expiration monitoring

### ISSUE THREAD

**Issue by aieri** [canonical/traefik-k8s-operator#380]
### Enhancement Proposal

As traefik can handle TLS termination for multiple services, it would be the perfect place for monitoring certificate expiration. This could for example be a metric indicating the time left until expiration, plus an alert rule firing 30 days prior to it.

Note: as an MSP, a (legacy) equivalent setup - [part](https://github.com/canonical/charm-openstack-service-checks/blob/main/src/files/plugins/check_ssl_cert) of openstack-service-checks - has been crucial for us in order to get the ball rolling in time for certificate renewals in Charmed OpenStack clouds. Traefik could do something similar for any service that relies on it (and be well integrated with COS).

**Comment by michaeldmitry** [comment]
@lucabello

**Comment by lucabello** [comment]
@aieri You can currently achieve this with [blackbox exporter](https://charmhub.io/blackbox-exporter-k8s).

Our docs have [this tutorial](https://charmhub.io/blackbox-exporter-k8s/docs/monitor-ssl-certificates) now which will help you do that :)

It's currently mostly a "manual" charm, so having Traefik as an aggregation point could be a nice future improvement!

Does this solve your issue? :)

**Comment by aieri** [comment]
hi @lucabello as an enhancement proposal I think this report should stay open (unless you disagree with it). Blackbox exporter can indeed be a temporary workaround

**Comment by sed-i** [comment]
Could probably address this with the new upcoming probes library - https://github.com/canonical/blackbox-exporter-k8s-operator/pull/43.

**Comment by dstathis** [comment]
My understanding is this is generally handled on the provider side of the tls_certificates relation. @gruyaume Can you confirm this?

**Comment by gruyaume** [comment]
> My understanding is this is generally handled on the provider side of the tls_certificates relation. @gruyaume Can you confirm this?

Agreed, metrics related to certificate expiration are typically going to be provided by workloads that generate those certificates. For instance [Vault](https://charmhub.io/vault-k8s) and [Notary](https://charmhub.io/notary-k8s) have such metrics.

**Comment by dstathis** [comment]
Closing this as it is handled by the cert provider.
