### ISSUE TITLE
add an action to export the server cert and ca cert

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/traefik-k8s-operator#390]
### Enhancement Proposal

when communicating with traefik from uncharmed applications it can be handy to obtain the certificates to enable TLS.
ATM the only way to do that for a cloud admin is to obtain the cert is via manually running openssl commands. This would be nicer API:

`juju run traefik/0 get-certificates`

similar actions would have to be implemented in the grafana agent charms

**Comment by ghislainbourgeois** [comment]
I would not say it is a common pattern per se, but it would not be uncommon either. In instances where the certificate is not issued by a public authority, there is a need to configure the clients with the issuing certificate authority. 

In manual operations, this would either be by getting the certificates configured on the gateway and installing them on the client's trust store, or get the issuing certificates from the central private authority and installing them in the trust store.

The most secure way would be using an out of band mechanism; meaning that the client gets the certificates from the certificate authority itself, and the gateway gets its certificate signed by that same authority.

Regarding this proposal more specifically, I think it can make sense. It let's a user do something they could already do in a nicer way.

I would suggest that in most cases, our documentation pushes to have the client obtain the issuing CA from the signing authority itself.

**Comment by michaeldmitry** [comment]
Since it is not considered a best practice, we should be only getting the CA from the provider not the gateway. Closing the issue.
