### ISSUE TITLE
Add integration tests for `ingress` and `ingress-per-unit`

### ISSUE THREAD

**Issue by jnsgruk** [canonical/traefik-k8s-operator#41]
We should have some basic tests in place that deploy traefik, and have it related on both the ingress, and ingress-per-unit interface.

More advanced tests should follow that switch the subdomain/path mode and test the available routes.

**Comment by mmanciop** [comment]
For ingress_per_unit, we should replicate https://github.com/canonical/prometheus-k8s-operator/blob/main/tests/integration/test_ingress_with_traefik_k8s.py here. I am honestly surprised I did not yet :-)
