### ISSUE TITLE
add a charm config to add custom annotations to loadbalancers created by traefik

### ISSUE THREAD

**Issue by nishant-dash** [canonical/traefik-k8s-operator#423]
### Enhancement Proposal

In the use case of deploying the COS stack with multiple traefiks for finer control over routing between the various components of COS, it will be super helpful if we could add custom annotations to loadbalancers.

**Comment by dparv** [comment]
+1 that's going to be useful for *all* public clouds as the way to change the behavior of load balances is usually trough the annotation definitions (e.g. aws, azure)

**Comment by natalytvinova** [comment]
+1 we are facing difficulties in control of the networking in Azure environment because of Azure and Juju assigning public IPs to all loadbalancers. It would be easily solved with internal annotations.

**Comment by AxoyTO** [comment]
> +1 we are facing difficulties in control of the networking in Azure environment because of Azure and Juju assigning public IPs to all loadbalancers. It would be easily solved with internal annotations.

+1
