### ISSUE TITLE
Hook failed: "storage-attached"

### ISSUE THREAD

**Issue by cleitonpena** [canonical/traefik-k8s-operator#62]
Congratulations for Charmed ingress on k8s.

I think now maybe I can get access to applications without Nginx Ingress.

I’m on Microk8s/Aws and for

juju deploy traefik-k8s --to 0

the return is:

`hook failed: “storage-attached”`

In the log appears:

```
File “/var/lib/juju/agents/unit-traefik-k8s-1/charm/lib/charms/observability_libs/v0/kubernetes_service_patch.py”, line 279, in _namespace with open("/var/run/secrets/kubernetes.io/serviceaccount/namespace", “r”) as f: FileNotFoundError: [Errno 2] No such file or directory: ‘/var/run/secrets/kubernetes.io/serviceaccount/namespace’ unit-traefik-k8s-1: 13:16:49 ERROR juju.worker.uniter.operation hook “configurations-storage-attached” (via hook dispatching script: dispatch) failed: exit status 1 unit-traefik-k8s-1: 13:16:49 INFO juju.worker.uniter awaiting error resolution for “storage-attached” hook
I also tried juju deploy from zinc-k8s and it returned the same error.
```

I am using cStor openebs for PVC in addition to the Microk8s default volumes configuration.

What can I do to get out of this impasse,  @PietroPasotti 

Thanks if you can answer

**Comment by sed-i** [comment]
- I wonder where the `storage-attached` is coming from because I do not see an observer for it.
- `--to` seems like it belongs somewhere else because `--to cannot be used on k8s models`.
- Can you try deploying with `--trust`?

**Comment by cleitonpena** [comment]
Thank you very much, @sed-i for helping me so quickly.
See that I deleted the --to and added --trust but the error persists, as in this log:

`unit-traefik-k8s-2: 22:19:03 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-traefik-k8s-2: 22:20:28 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook
unit-traefik-k8s-2: 22:20:28 ERROR unit.traefik-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 501, in <module>
    main(TraefikIngressCharm)
  File "/var/lib/juju/agents/unit-traefik-k8s-2/charm/venv/ops/main.py", line 414, in main
    charm = charm_class(framework)
  File "./src/charm.py", line 73, in __init__
    self.service_patch = KubernetesServicePatch(
  File "/var/lib/juju/agents/unit-traefik-k8s-2/charm/lib/charms/observability_libs/v0/kubernetes_service_patch.py", line 143, in __init__
    self.service = self._service_object(
  File "/var/lib/juju/agents/unit-traefik-k8s-2/charm/lib/charms/observability_libs/v0/kubernetes_service_patch.py", line 199, in _service_object
    namespace=self._namespace,
  File "/var/lib/juju/agents/unit-traefik-k8s-2/charm/lib/charms/observability_libs/v0/kubernetes_service_patch.py", line 279, in _namespace
    with open("/var/run/secrets/kubernetes.io/serviceaccount/namespace", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/namespace'
unit-traefik-k8s-2: 22:20:28 ERROR juju.worker.uniter.operation hook "configurations-storage-attached" (via hook dispatching script: dispatch) failed: exit status 1
unit-traefik-k8s-2: 22:20:28 INFO juju.worker.uniter awaiting error resolution for "storage-attached" hook`

**Comment by PietroPasotti** [comment]
My feeling about this is that you're trying to deploy on a non-kubernetes environment. The fact that the hook is failing on the k8s service patch seems to indicate that too.
Could you post the (relevant parts of):

`juju clouds`

`juju controllers`

`juju models`

`juju status`

**Comment by cleitonpena** [comment]
Thank you so much @PietroPasotti for the so quick support. With your next analysis, I will be able to better understand your feeling about my problem. But please see what is wrong in the following information:

- juju status

`Clouds available on the controller:
Cloud  Regions  Default    Type
aws    22       us-west-2  ec2  `

- juju controllers

`Controller     Model      User                  Access     Cloud/Region   Models  Nodes    HA  Version
aws-us-west-2  test       admin                 superuser  aws/us-west-2       5      1  none  2.9.26  
jaas           privcloud  penacleiton@external  (unknown)                      -      -     -  2.9.18  
micro*         pe6k8      admin                 superuser  aws/us-west-2       3      5  none  2.9.26 `

- juju models

`Controller: micro

Model       Cloud/Region   Type  Status     Machines  Cores  Units  Access  Last connection
controller  aws/us-west-2  ec2   available         1      2  -      admin   just now
default     aws/us-west-2  ec2   available         0      -  -      admin   6 hours ago
pe6k8*      aws/us-west-2  ec2   available         4      8  4      admin   7 minutes ago`

- juju status

`Model  Controller  Cloud/Region   Version  SLA          Timestamp
pe6k8  micro       aws/us-west-2  2.9.26   unsupported  05:16:38-04:00

App       Version  Status  Scale  Charm     Channel  Rev  Exposed  Message
gitlab    20.04    active      1  ubuntu    stable    18  no       
microk8s           active      3  microk8s  stable    21  yes      

Unit         Workload  Agent  Machine  Public address  Ports      Message
gitlab/0*    active    idle   3        44.238.97.226              
microk8s/0*  active    idle   0        54.188.57.179   16443/tcp  
microk8s/1   active    idle   1        35.155.84.87    16443/tcp  
microk8s/2   active    idle   2        44.232.143.220  16443/tcp  

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  54.188.57.179   i-0240a86db78f3bf54  focal   us-west-2c  running
1        started  35.155.84.87    i-0c50ab4e2ee2d75a1  focal   us-west-2a  running
2        started  44.232.143.220  i-022da0c3eb5730dc8  focal   us-west-2b  running
3        started  44.238.97.226   i-0eab9810e0f004f88  focal   us-west-2c  running`

**Comment by PietroPasotti** [comment]
Yes, I think my suspicions were correct, you are not on kubernetes :) 
I'll refer you to https://juju.is/docs/olm/get-started-on-kubernetes on how to get started with juju on k8s

**Comment by PietroPasotti** [comment]
(We are investigating whether Juju should or not have given an earlier warning of what was going on...)
stay tuned: https://bugs.launchpad.net/juju/+bug/1979067
