### ISSUE TITLE
Replace jsonschema with pydantic

### ISSUE THREAD

**Issue by simskij** [canonical/traefik-k8s-operator#65]
The traefik libraries would be excellent candidates for trying out replacing jsonschema with pydantic. According to lessons learned by the charmcraft team, pydantic plays a lot nicer with more complex data structures, is faster in the general use case and has better error logging.

In addition to the swap, it would be excellent if we generated the pydantic model from the json schemas of the interface spec.

**Comment by simskij** [comment]
> I don't disagree here, but we should be cautious merging, as it will essentially be a breaking change due to changing the external requirements of the lib :) I'm interested to see the diff in the code though.

Agreed. Given that @PietroPasotti is working on v1 of the libs (https://github.com/canonical/traefik-k8s-operator/pull/63/files#), which essentially will be incompatible regardless, it feels like it could be a good time to do both these changes at the same time to not have break the compatibility twice. :)

**Comment by simskij** [comment]
I'm thinking we'd use the [datamodel-code-generator](https://pydantic-docs.helpmanual.io/datamodel_code_generator/), probably as part of the CI of the relation interfaces repo itself, and that users then would be able to download the pydantic model straight from github and use it in their projects.

**Comment by PietroPasotti** [comment]
@jnsgruk @simskij  see #66

**Comment by dstathis** [comment]
We are already using pydantic.
