### ISSUE TITLE
TLS encryption to proxied workloads

### ISSUE THREAD

**Issue by mmanciop** [canonical/traefik-k8s-operator#7]
It should be possible for requesters of the `ingress-per-unit` relation to ask for Traefik to establish TLS when routing requests to them. This, in turn, requires extending the relation data protocol to allow the specification of CA and Server certificates submitted by single units and/or Juju applications.

Note: This issue is *not* about providing TLS to Traefik itself from the outside of the Kubernetes cluster, which is covered by #6.

**Comment by PietroPasotti** [comment]
@sed-i we can close this one, right?

**Comment by sed-i** [comment]
Not yet, this is about internal TLS. #100 is just for termination (external).

**Comment by dstathis** [comment]
We have this.
